## Exercise 6 - Numpy

1 Generate two NumPy arrays so that first array has integers from 10 to 40 (inclusive). Second array should have integers from 220 to 250 (inclusive). Sum these arrays and present the result array.

In [42]:
import numpy as np

arr1 = np.arange(10,41)
arr2 = np.arange(220,251)

#print(arr1)
#print(arr2)

def sum_array(arr1,arr2):
    print("Sum of \n{} and \n{}".format(arr1,arr2))
    print("Result: \n{}".format(arr1 + arr2))

sum_array(arr1,arr2)

Sum of 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40] and 
[220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237
 238 239 240 241 242 243 244 245 246 247 248 249 250]
Result: 
[230 232 234 236 238 240 242 244 246 248 250 252 254 256 258 260 262 264
 266 268 270 272 274 276 278 280 282 284 286 288 290]


2 Generate two-dimensional array with 10 rows and 7 columns containing integers starting from 100.

In [43]:
arr3 = np.arange(100,170).reshape(10,7)

arr3

array([[100, 101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127],
       [128, 129, 130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139, 140, 141],
       [142, 143, 144, 145, 146, 147, 148],
       [149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162],
       [163, 164, 165, 166, 167, 168, 169]])

3 Generate two one-dimensional arrays having integers between 1-50. First array should have even and second array should have odd numbers. Finally multiply each element from corresponding index positions from these two arrays for the result array. For example [(1 x 2),(3 x 4),(5 x 6),(7 x 8)...].

In [44]:
arr4 = np.arange(0,50,2)
arr5 = np.arange(1,50,2)

print("Even numbers array: ", arr4)
print("Odd numbers array: ", arr5)

multiply = arr4 * arr5

print("Each element multiplied from corresponding index position: \n", multiply)

Even numbers array:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Odd numbers array:  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
Each element multiplied from corresponding index position: 
 [   0    6   20   42   72  110  156  210  272  342  420  506  600  702
  812  930 1056 1190 1332 1482 1640 1806 1980 2162 2352]


4 Generate two-dimensional array (40 rows, 5 columns) containing random integers between 1 and 1000. Filter the result array so that only numbers divisable with numbers 2 and 5 are presented (number must be divisable with both).

In [52]:
arr6 = np.random.randint(1,1000,200)
arr6_new = arr6.reshape(40,5)

arr6_new


array([[880, 107, 524, 926, 602],
       [801, 959, 135, 699, 155],
       [136, 605, 674, 957, 944],
       [552, 715, 922, 381, 584],
       [940, 956, 619,  89, 532],
       [851, 891, 209, 531, 741],
       [473, 950, 437, 397, 149],
       [233, 999, 870, 155, 106],
       [486, 713, 227, 834, 844],
       [990, 956, 666, 214, 312],
       [639, 749, 366, 147, 590],
       [774, 853, 308,  16, 427],
       [108, 739, 543, 362, 204],
       [465, 740, 657, 596,  66],
       [609, 229, 905, 952, 322],
       [121, 772, 346,  34, 825],
       [185,  13, 367, 548, 793],
       [470, 154, 391, 186, 655],
       [893, 446, 858, 475, 160],
       [519, 952, 906, 697, 267],
       [755, 891, 544, 504, 886],
       [772, 294, 757, 565, 194],
       [255, 232, 226, 359, 738],
       [570,  66, 337, 838, 798],
       [438, 243, 228, 608, 242],
       [ 78, 985, 575, 238, 399],
       [968, 900, 749, 242, 989],
       [245, 973, 283, 929, 207],
       [362, 225, 615, 642, 536],
       [955, 7

In [63]:
#result_array = np.where((arr6_new % 2 == 0)) # provides index numbers

result_array = arr6_new[(arr6_new % 2 == 0) & (arr6_new % 5 == 0)]
print("Result array: \n", result_array)

Result array: 
 [880 940 950 870 990 590 740 470 160 570 900  20 200 690 510 330]
